### ISSUE TITLE
No config

### ISSUE THREAD

**Issue by zsdxgl** [Godotcoffee/AlignGraph2#2]
Dear Godotcoffee,

Traceback (most recent call last):
  File "AlignGraph2/AlignGraph2.py", line 389, in <module>
    script.split_helper.split_pre_process(ctg_path, ref_path, ctg_to_ref_path, input_dir, sp_input_dir)
  File "/AlignGraph2/script/split_helper.py", line 21, in split_pre_process
    with open(cfg_path, 'r') as cf:
FileNotFoundError: [Errno 2] No such file or directory: '/working_dir/input/p/config.txt'

An error ocurred. Any suggestion?

**Comment by Godotcoffee** [comment]
Sorry for taking so long to reply. Because this project is now mainly maintained [there](https://github.com/huangs001/AlignGraph2), I didn't see this issue immediately. According to the description, the problem may be caused by the module "pre_process" (runs in the AlignGraph2.py, line 369, the executable file located in "AlignGraph2/PAGraph/build/pre_process"). The "pre_process" must ensure that there is output to "working_dir/input/p/config.txt". But now I don't know the exact problem, you can try print the command details of line 369 and manually run at the command line to see what happens.
